import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    // sitemap.xml is generated by the API (it needs the live product list).
    // In production, rewrite the storefront's /sitemap.xml to the API the same way.
    proxy: {
      '/sitemap.xml': 'http://localhost:4000',
    },
  },
})
